version: 0.0
os: linux
files:
  - source: /
    destination: /opt/codedeploy-agent/
    overwrite: true
file_exists_behavior: OVERWRITE
permissions:
  - object: /opt/codedeploy-agent/
    pattern: "**"
    owner: ec2-user
    group: apache
    mode: "777"
hooks:
  BeforeInstall:
    - location: install_dependencies.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: start_server.sh
      timeout: 300
      runas: root
