version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/myapp/
permissions:
  - object: /var/www/html/myapp
    pattern: "**"
    owner: ec2-user
    group: apache
    mode: "777"
  - object: /var/www/html/myapp/node_modules
    pattern: "**"
    owner: ec2-user
    group: apache
    mode: "777"
  - object: /var/www/html/myapp/logs
    pattern: "**"
    owner: ec2-user
    group: apache
    mode: "777"
hooks:
  BeforeInstall:
    - location: install_dependencies.sh
      timeout: 300
      runas: root
    - location: start_server.sh
      timeout: 300
      runas: root
